apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: DotnetwebapiDeployment
spec: 
  selector: 
    matchLabels: 
      app: testwebapi 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: testwebapi 
    spec: 
      containers: 
      - name: Rajesh110 
        image:rajesh110.azurecr.io/dockertestapi
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: DotnetwebapiDeployment
spec: 
  selector: 
    app: testwebapi 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 